version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://umutduran:123456@mysql:3306/WebApp  # MySQL bilgileri
  mysql:
     image: mysql:latest
     restart: always
     ports:
      - "3306:3306"  # Host:Container
     environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: WebApp
      MYSQL_USER: umutduran
      MYSQL_PASSWORD: 123456
